spring.application.name=ScreenMatch

spring.datasource.url=jdbc:postgresql://db.wbdanmkyoixmsaffimbo.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=phelipegitorg
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

jwt.secret=fgjidfigifgjidfgdfmbkdfbcvbcpvmbppodgfkopgdfgdf
jwt.expiration=10000000000000

