spring.application.name=ScreenMatch

server.port=${SERVER.PORT}

spring.datasource.url=${SPRING.DATASOURCE.URL}
spring.datasource.USERNAME=${SPRING.DATASOURCE.USERNAME}
spring.datasource.password=${SPRING.DATASOURCE.PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING.JPA.HIBERNATE.DDL-AUTO}
spring.jpa.show-sql=${SPRING.JPA.SHOW-SQL}

jwt.secret=${JWT.SECRET}
jwt.expiration=${JWT.EXPIRATION}